// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Simulates bot typing speeds based on the user's performance.
 *
 * - simulateBotSpeed - A function that simulates the bot speed.
 * - SimulateBotSpeedInput - The input type for the simulateBotSpeed function.
 * - SimulateBotSpeedOutput - The return type for the simulateBotSpeed function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SimulateBotSpeedInputSchema = z.object({
  userWpm: z.number().describe('The user words per minute.'),
  userElo: z.number().describe('The user elo ranking.'),
  raceDuration: z.number().describe('The duration of the race in seconds.'),
});
export type SimulateBotSpeedInput = z.infer<typeof SimulateBotSpeedInputSchema>;

const SimulateBotSpeedOutputSchema = z.object({
  botWpm: z.number().describe('The simulated bot words per minute.'),
});
export type SimulateBotSpeedOutput = z.infer<typeof SimulateBotSpeedOutputSchema>;

export async function simulateBotSpeed(input: SimulateBotSpeedInput): Promise<SimulateBotSpeedOutput> {
  return simulateBotSpeedFlow(input);
}

const prompt = ai.definePrompt({
  name: 'simulateBotSpeedPrompt',
  input: {schema: SimulateBotSpeedInputSchema},
  output: {schema: SimulateBotSpeedOutputSchema},
  prompt: `You are simulating the typing speed of a bot in a typing race.

  The user has a WPM of {{userWpm}} and an elo of {{userElo}}. The race duration is {{raceDuration}} seconds.

  Simulate a bot WPM that is slightly slower than the user, but still challenging.
  Take into account the elo of the user, and increase the bot speed slightly as the user elo increases.

  Return only the bot WPM as a number.
  `,
});

const simulateBotSpeedFlow = ai.defineFlow(
  {
    name: 'simulateBotSpeedFlow',
    inputSchema: SimulateBotSpeedInputSchema,
    outputSchema: SimulateBotSpeedOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
